# Generated by Django 5.0.3 on 2024-04-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_text_question_body_question_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
